name: Events Demo 1
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run:  echo "${{toJSON(github.event)}}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
              node-version: 18
      - name: Install dependencies
        run:  |
              cd ./Starting_Project_New
              npm ci
      - name: Test code
        run:  |
              cd ./Starting_Project_New
              npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."