name: Practice Project
on: push
jobs:
    run-linter:
        runs-on: ubuntu-latest
        steps:
            - name : Checkout repo
              uses: actions/checkout@v4
            - name: Install Nodejs
              uses: actions/setup-node@v4
              with:
                    node-version: 18
            - name: install eslint
              run: npm install eslint --save-dev
            - name: Install Dependencies
              run:  |
                    cd ./practice_project && npm ci
            - name: run eslint
              run:  |
                    cd ./practice_project && npm eslint .
