name: Practice Project
on: push
jobs:
    run-linter:
        runs-on: ubuntu-latest
        steps:
            - name : Checkout repo
              uses: actions/checkout@v4
            - name: Install Nodejs
              uses: actions/setup-node@v4
              with:
                    node-version: 18
            - name: install eslint
              run: npm install eslint --save-dev
            - name: Install Dependencies
              run:  |
                    cd ./practice_project && npm ci
            - name: run eslint
              run:  |
                    cd ./practice_project && npx eslint .
    run-tests:
        runs-on: ubuntu-latest
        needs: run-linter
        steps:
            - name : Checkout repo
              uses: actions/checkout@v4
            - name: Install Nodejs
              uses: actions/setup-node@v4
              with:
                    node-version: 18
            - name: Install Dependencies
              run:  |
                    cd ./practice_project
                    npm ci
            - name: Run Tests
              run:  |
                    cd ./practice_project
                    npm test
    build-project:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - name : Checkout repo
              uses: actions/checkout@v4
            - name: Install Nodejs
              uses: actions/setup-node@v4
              with:
                    node-version: 18
            - name: Install Dependencies
              run:  |
                    cd ./practice_project
                    npm ci
            - name: Build Project
              run:  |
                    cd ./practice_project
                    npm run build
                    echo "Project Built Successfully"
    Output-Event-Details:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - name: Output Event Details
              run: echo "${{toJSON(github.event)}}"
