name: Test Project
on: push #define the event when to run the workflow
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code from repository
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Print working directory
              run: pwd
            - name: Install Dependencies
              run: |
                  cd ./starting_project && npm ci
            - name: Run Tests
              run: |
                  cd ./starting_project && npm test